### PR TITLE
Process improvements

### PR DESCRIPTION
**Pull request by parruda**
Can only be merged after #1

### CODE REVIEW

**Comment by tylerklose** [comment]
Interesting GitHub bot that we use at work, prevents merging of PRs that have WIP in the title: https://probot.github.io/apps/wip/

**Comment by parruda** [comment]
Great one! I added it to all repos.

**Comment by parruda** [comment]
@tylerklose Need to merge this one now!

**Comment by tylerklose** [comment]
@parruda running into some issues here with `puma`:
```console
tk@tk-macbook-pro email-scheduler (master)*$ ps ax | grep puma
50913 s003  S+     0:00.00 grep puma
tk@tk-macbook-pro email-scheduler (master)*$ gotta serve
Puma starting in single mode...
* Version 3.12.1 (ruby 2.6.1-p33), codename: Llamas in Pajamas
* Min threads: 10, max threads: 20
* Environment: development
#<Thread:0x00007fafc71c0ec0@/Users/tk/code/source/gotta-dev/gotta/lib/gotta/serve/config/config.ru:12 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	3: from /Users/tk/code/source/gotta-dev/gotta/lib/gotta/serve/config/config.ru:15:in `block (2 levels) in <main>'
	2: from /Users/tk/code/source/gotta-dev/gotta/lib/gotta/queue/socket/server.rb:36:in `start'
	1: from /Users/tk/code/source/gotta-dev/gotta/lib/gotta/queue/socket/server.rb:36:in `new'
/Users/tk/code/source/gotta-dev/gotta/lib/gotta/queue/socket/server.rb:36:in `initialize': Address already in use - bind(2) for "0.0.0.0" port 1414 (Errno::EADDRINUSE)
Traceback (most recent call last):
	21: from /Users/tk/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
	20: from /Users/tk/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
	19: from /Users/tk/.rvm/gems/ruby-2.6.1/bin/gotta:23:in `<main>'
	18: from /Users/tk/.rvm/gems/ruby-2.6.1/bin/gotta:23:in `load'
	17: from /Users/tk/.rvm/gems/ruby-2.6.1/gems/gotta-0.1.2/exe/gotta:20:in `<top (required)>'
	16: from /Users/tk/code/source/gotta-dev/gotta-cli/lib/gotta/cli.rb:28:in `run'
	15: from /Users/tk/code/source/gotta-dev/gotta-cli/lib/gotta/cli.rb:28:in `new'
	14: from /Users/tk/code/source/gotta-dev/gotta-cli/lib/gotta/cli/command.rb:77:in `initialize'
	13: from /Users/tk/code/source/gotta-dev/gotta-cli/lib/gotta/cli/command.rb:85:in `build_command'
	12: from /Users/tk/code/source/gotta-dev/gotta-cli/lib/gotta/cli/command.rb:85:in `each'
	11: from /Users/tk/code/source/gotta-dev/gotta-cli/lib/gotta/cli/command.rb:94:in `block in build_command'
	10: from /Users/tk/code/source/gotta-dev/gotta/lib/gotta/serve/cli/serve.rb:37:in `run!'
	 9: from /Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/cli.rb:80:in `run'
	 8: from /Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/launcher.rb:186:in `run'
	 7: from /Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/single.rb:98:in `run'
	 6: from /Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/runner.rb:153:in `load_and_bind'
	 5: from /Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/binder.rb:90:in `parse'
	 4: from /Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/binder.rb:90:in `each'
	 3: from /Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/binder.rb:106:in `block in parse'
	 2: from /Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/binder.rb:273:in `add_tcp_listener'
	 1: from /Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/binder.rb:273:in `new'
/Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/binder.rb:273:in `initialize': Address already in use - bind(2) for "0.0.0.0" port 3000 (Errno::EADDRINUSE)
```

**Comment by parruda** [comment]
`Address already in use - bind(2) for "0.0.0.0" port 3000 (Errno::EADDRINUSE)`

Maybe you have a dead puma in background from a previous error? It happened on my machine once. Try killing the process!

**Comment by tylerklose** [comment]
`ps ax | grep <term>` where `<term>` is `puma`, `0.0.0.0`, or `3000` shows no matches. Is there a better way to search for alive processes?

**Comment by tylerklose** [comment]
> `ps ax | grep <term>` where `<term>` is `puma`, `0.0.0.0`, or `3000` shows no matches. Is there a better way to search for alive processes?

`ps ax | gotta-serve` did the trick! @parruda sent me this via Slack, but I figured it would be good to document it somewhere

**Comment by tylerklose** [comment]
Are you seeing this as well? I'm just going to `localhost:3000` or `localhost:3000/catch_all`
```
uninitialized constant Gotta::Serve::Server::Timeout:
	/Users/tk/code/source/gotta-dev/gotta/lib/gotta/serve/server.rb:77:in `rescue in block in <class:Server>'
	/Users/tk/code/source/gotta-dev/gotta/lib/gotta/serve/server.rb:73:in `block in <class:Server>'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/logger.rb:15:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/common_logger.rb:33:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:231:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:224:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/show_exceptions.rb:22:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
	/Users/tk/.rvm/gems/ruby-2.6.1/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by tylerklose** [comment]
On the topic of `catch_all`, I believe the previous default was `catch-all`. Do you have a preference for underscores?

**Comment by parruda** [comment]
> On the topic of `catch_all`, I believe the previous default was `catch-all`. Do you have a preference for underscores?

Not really. It doesn't matter to me.

**Comment by parruda** [comment]
> Are you seeing this as well? I'm just going to `localhost:3000` or `localhost:3000/catch_all`

Somewhere there's a `::` missing in front of Timeout

**Comment by parruda** [comment]
@tylerklose Added missing `require 'timeout'`

**Comment by tylerklose** [comment]
> > On the topic of `catch_all`, I believe the previous default was `catch-all`. Do you have a preference for underscores?
> 
> Not really. It doesn't matter to me.

I know there used to be a difference between using `-` and `_` in URLs for SEO purposes. I don't know if that's still the case. If it is, we might want to go with `catch-all` so it's consistent with the names of other SEO-friendly routes

**Comment by tylerklose** [comment]
No longer running into the same Timeout issue, but now I'm seeing Execution timeout when I go to `localhost:3000`.

```console
[root] <- [REQUEST: GET "/"] request_id="f18c00b1-ac28-4c90-90b8-ca90ecb67966" body=nil query_params={} headers={"Version"=>"HTTP/1.1", "Host"=>"localhost:3000", "Accept"=>"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Upgrade-Insecure-Requests"=>"1", "Cookie"=>"__utma=111872281.1222849612.1536247516.1547497896.1547504386.116; __utmz=111872281.1536247516.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); wm-stpcond-14-90138-x=1; wm-ASRep-14-90138=1; "User-Agent"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15", "Accept-Language"=>"en-us", "Accept-Encoding"=>"gzip, deflate", "Connection"=>"keep-alive", "Content-Type"=>nil, "Request-Method"=>"GET", "Content-Length"=>nil, "Remote-Addr"=>"127.0.0.1", "X-Request-Id"=>"f18c00b1-ac28-4c90-90b8-ca90ecb67966"}
[root] -> [RESPONSE: 60ms] request_id="f18c00b1-ac28-4c90-90b8-ca90ecb67966" status=504 body="Execution timeout" headers={"Content-Type"=>"text/plain", "X-Request-Id"=>"f18c00b1-ac28-4c90-90b8-ca90ecb67966", "X-Execution-time"=>"60ms"}
127.0.0.1 - - [18/Jun/2019:06:50:40 -0400] "GET / HTTP/1.1" 504 17 3.0042
```

**Comment by parruda** [comment]
I can't make the changes without breaking the redis branch.
Let's merge this and the fix will come shortly.

**Pull request merged**
